name: garn
version: 0.1.0.0
github: "garnix-io/garn"
author: "garnix"
maintainer: "contact@garnix.io"
copyright: "AllRightsReserved"

verbatim:
  data-files: |
    ts/**/*.ts
    ts/**/*.json
  cabal-version: 2.4

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FunctionalDependencies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLabels
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ScopedTypeVariables
  - StandaloneDeriving

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - ansi-wl-pprint
  - containers
  - cradle
  - directory
  - getopt-generics
  - interpolate
  - optparse-applicative
  - pretty-simple
  - process
  - string-conversions
  - template-haskell
  - temporary
  - text
  - unix

ghc-options:
  - -Wall
  - -with-rtsopts=-T
  - -threaded
  - -Wno-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test/spec
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fdefer-typed-holes
    dependencies:
      - async
      - filepath
      - hspec
      - hspec-discover
      - hspec-discover
      - hspec-golden
      - http-client
      - lens
      - lens-aeson
      - lens-regex-pcre
      - mockery
      - pcre-heavy
      - shake
      - silently
      - strip-ansi-escape
      - wreq
      - yaml

library:
  source-dirs:
    - src

executables:
  garn:
    main: exe/garn.hs
    dependencies:
      - garn

  codegen:
    main: exe/codegen.hs
    dependencies:
      - garn
