name: garner
version: 0.1.0.0
github: "garnix-io/garner"
license: AllRightsReserved
author: "garnix"
maintainer: "contact@garnix.io"
copyright: "AllRightsReserved"

data-files:
  - ts/base.ts
  - ts/runner.ts

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FunctionalDependencies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLabels
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ScopedTypeVariables
  - StandaloneDeriving

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - directory
  - getopt-generics
  - interpolate
  - process
  - shake
  - string-conversions
  - temporary
  - text
  - unix

ghc-options:
  - -Wall
  - -with-rtsopts=-T
  - -Wno-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test/spec
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fdefer-typed-holes
    dependencies:
      - http-client
      - hspec
      - hspec-discover
      - hspec-discover
      - hspec-golden
      - lens
      - lens-aeson
      - mockery
      - silently
      - wreq
      - yaml

library:
  source-dirs:
    - src

executables:
  garner:
    main: exe/garner.hs
    dependencies:
      - garner

  codegen:
    main: exe/codegen.hs
    dependencies:
      - garner
